# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-25 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_post_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_text', models.TextField()),
                ('comments_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.Post')),
            ],
        ),
    ]
